### ISSUE TITLE
Unhandled Exception...

### ISSUE THREAD

**Issue by jonsmith127** [Marekkon5/beatporttagger#10]
Hi, I'm getting this error when running on Python 3.6, any help to fix the problem would be much appreciated!

Unhandled Exception: Python.Runtime.PythonException: Exception : The callee (server [not server application]) is not available and disappeared; all connections are invalid. The call may have executed. (Exception from HRESULT: 0x80010007 (RPC_E_SERVER_DIED))
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by bascurtiz** [comment]
Running from source or a release/compiled one?

**Comment by jonsmith127** [comment]
I have been running from source on Python 3.6 but also get the same error when running the standalone beatporttagger.exe

**Comment by bascurtiz** [comment]
Can't reproduce - need more info.
Os ? version? 32 or 64 bit?

**Comment by jonsmith127** [comment]
Processor: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz
Installed RAM: 16.0 GB
System type: 64-bit operating system, x64-based processor
Edition	Windows: 10 Pro
Version: 20H2
OS build: 19042.685

**Comment by bascurtiz** [comment]
I assume you are running as Admin, which isn't possible with Webview (a module used in Beatport Tagger).
Try to run it without Admin rights.
In order to do so, make sure UAC is enabled.

More info that could lead to solution:
https://www.codeproject.com/Answers/5264285/Working-with-webview-control-in-windows-forms
https://kb.blackbaud.com.au/articles/Article/55361
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/223#issuecomment-572356030

**Comment by jonsmith127** [comment]
I created another user account without Admin rights and Beatporttagger is now working fine!

Problem solved, thank you for your help and thank you for developing this very useful program.
