### ISSUE TITLE
Empty GUI after compilling!

### ISSUE THREAD

**Issue by rosgr100** [Marekkon5/beatporttagger#3]
Hi, i was able to compile the .exe file but the UI is blank.

![Screenshot 2020-11-11 003159](https://user-images.githubusercontent.com/74199552/98741583-d334e580-23a4-11eb-9a46-22d762af3660.jpg)

**Comment by Marekkon5** [comment]
Could you try running from source to see if it works?

**Comment by rosgr100** [comment]
> 
> 
> Could you try running from source to see if it works?

Not it doesn't

C:\Users\rosGR\Desktop\beatporttagger-1.1.4> python beatporttagger.py
C:\Users\rosGR\AppData\Roaming\Python\Python36\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

Unhandled Exception: Python.Runtime.PythonException: Exception : The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
PS C:\Users\rosGR\Desktop\beatporttagger-1.1.4>

**Comment by Marekkon5** [comment]
Looks like broken python (or dependency). Could you tell me your python version? Can you try on 3.6.x (because it worked on Windows the best for me).

**Comment by rosgr100** [comment]
> 
> 
> Looks like broken python (or dependency). Could you tell me your python version? Can you try on 3.6.x (because it worked on Windows the best for me).

I am using the 3.6 already. I followed your instructions just to be sure that everything will work fine!

> C:\Users\rosGR\Desktop\beatporttagger-1.1.4> python --version
Python 3.6.0

**Comment by Marekkon5** [comment]
1. Maybe try newer Python? (Might help, personally using 3.8 on Linux).

2. You can force cef GUI - but for me it only worked when running from source (not exe build). You can do it by adding `, gui='cef'` to the last line in beatporttagger.py.

**Comment by Marekkon5** [comment]
If you're gonna try #2 - do `pip install cefpython3` to install it.

**Comment by rosgr100** [comment]
> 
> 
> If you're gonna try #2 - do `pip install cefpython3` to install it.

Would you please post the last three lines of beatporttagger.py with the addition of `, gui='cef'` because i do something wrong!

**Comment by Marekkon5** [comment]
```
if __name__ == '__main__':
    webview.start(debug=False, gui='cef')
```

**Comment by rosgr100** [comment]
Using python 3.8 gives me the exact same result as 3.6.

Something else i notice is that the original exe file is ~81Mb but the one i compile is ~37MB.

**Comment by rosgr100** [comment]
> if __name__ == '__main__':
>     webview.start(debug=False, gui='cef')

Not working either!

> PS C:\Users\rosGR\Desktop\beatporttagger-1.1.4> python beatporttagger.py
C:\Users\rosGR\AppData\Roaming\Python\Python38\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "beatporttagger.py", line 67, in <module>
    webview.start(debug=False, gui='cef')
  File "C:\Users\rosGR\AppData\Roaming\Python\Python38\site-packages\webview\__init__.py", line 96, in start
    guilib = initialize(gui)
  File "C:\Users\rosGR\AppData\Roaming\Python\Python38\site-packages\webview\guilib.py", line 98, in initialize
    if not try_import(guis):
  File "C:\Users\rosGR\AppData\Roaming\Python\Python38\site-packages\webview\guilib.py", line 62, in try_import
    if import_func():
  File "C:\Users\rosGR\AppData\Roaming\Python\Python38\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "C:\Users\rosGR\AppData\Roaming\Python\Python38\site-packages\webview\platforms\winforms.py", line 72, in <module>
    from . import cef as CEF
  File "C:\Users\rosGR\AppData\Roaming\Python\Python38\site-packages\webview\platforms\cef.py", line 12, in <module>
    from cefpython3 import cefpython as cef
  File "C:\Users\rosGR\AppData\Local\Programs\Python\Python38\lib\site-packages\cefpython3\__init__.py", line 64, in <module>
    raise Exception("Python version not supported: " + sys.version)
Exception: Python version not supported: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
PS C:\Users\rosGR\Desktop\beatporttagger-1.1.4>

**Comment by Marekkon5** [comment]
The cef patch - use python 3.6 or 3.7. 3.8 isnt supported with cef.

**Comment by rosgr100** [comment]
> 
> 
> The cef patch - use python 3.6 or 3.7. 3.8 isnt supported with cef.

With the python 3.6 and the `, gui='cef'` beatport tagger is launching when i run it through sources!

**Comment by Marekkon5** [comment]
Great, hopefully you can temporarily use it like that. You can try compiling to exe, but it wont probably work. Ill take a look at the issues tomorrow.

**Comment by rosgr100** [comment]
> 
> 
> Great, hopefully you can temporarily use it like that. You can try compiling to exe, but it wont probably work. Ill take a look at the issues tomorrow.

As long as i can use it i'm fine! 
Take your time!
Thank you for the help and the guidance!
Great work, thanks for sharing!

**Comment by mcanaleta** [comment]
I have the same issue. Updating pywebview-3.3.3 to pywebview-3.3.5 solves the issue for me:

>(env)
mcana@DESKTOP-RD1NGHU MINGW64 ~/projects/beatporttagger (main)
$ git diff
diff --git a/requirements.txt b/requirements.txt
index 3bad8ff..f7caeff 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,7 +1,7 @@
 requests==2.22.0
 fuzzywuzzy==0.17.0
 mutagen==1.42.0
-pywebview==3.3.3
+pywebview==3.3.5
 beautifulsoup4==4.9.3
 PyQt5==5.15.1
 lxml==4.6.1
\ No newline at end of file

> (env)
mcana@DESKTOP-RD1NGHU MINGW64 ~/projects/beatporttagger (main)
$ python -VV
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]

**Comment by rosgr100** [comment]
> 
> 
> I have the same issue. Updating pywebview-3.3.3 to pywebview-3.3.5 solves the issue for me:
> 
> > (env)
> > mcana@DESKTOP-RD1NGHU MINGW64 ~/projects/beatporttagger (main)
> > $ git diff
> > diff --git a/requirements.txt b/requirements.txt
> > index 3bad8ff..f7caeff 100644
> > --- a/requirements.txt
> > +++ b/requirements.txt
> > @@ -1,7 +1,7 @@
> > requests==2.22.0
> > fuzzywuzzy==0.17.0
> > mutagen==1.42.0
> > -pywebview==3.3.3
> > +pywebview==3.3.5
> > beautifulsoup4==4.9.3
> > PyQt5==5.15.1
> > lxml==4.6.1
> > \ No newline at end of file
> 
> > (env)
> > mcana@DESKTOP-RD1NGHU MINGW64 ~/projects/beatporttagger (main)
> > $ python -VV
> > Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]

Yeap this solves the problem!

Thank you!

Just change the `pywebview==3.3.3` to `pywebview==3.3.5` in the requirements.txt, this will do the trick!
